### ISSUE TITLE
Adding a way of having a library of slide types

### ISSUE THREAD

**Issue by qume** [slideshow-templates/slideshow-s5-themes#1]
Hello, thanks for the great work on this. It looks like a great starting point for what I need for a project.

I thought I'd get in touch to ask you how you would go about extending this before starting myself.

I need to be able to select a slide type in the markup, such that there can be a number of pre-prepared slide styles to choose from. Some optimised for images, some for two column, etc.

What would be your approach to doing this? 

Thank you very much
Luke

**Comment by geraldb** [comment]
Good idea. Thanks for the suggestion.  You can create slide types with ruby helpers (and include the helpers via plugins). See the %left %right or %table helpers as an example. Cheers.
